name: Codacy-Scan

on:
  workflow_dispatch

jobs:
  action:
    name: Codacy SAST Scan
    uses: Fortiwatch/advanced-security-compliance/.github/workflows/codeacy-analysis.yml@v1
    with:
      output: results.sarif
