name: Codacy-Scan

on:
  workflow_dispatch

jobs:
  action:
    name: Codacy SAST Scan
    uses: Fortiwatch/advanced-security-compliance/.github/workflows/codeacy-analysis.yml@main
    with:
      directory: ./terraform/
      tool: checkov
