# This is a starter workflow to help you get started with scanning Terraform using Actions

name: IAC Code Scan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   iac-sec-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with:
        # api-key: ${{ secrets.API_KEY }}
        quiet: true # Optional: Display only failed check
        soft_fail: true # Optional: Do not return an error code if there are failed checks
        output_format: cli # Optional: The output format, one of: cli, json, junitxml, github_failed_only
        #check: # Optional: Run only a specific check_id, can be a comma separated list (details at bridgecrewio/checkov/docs/3.Scans/resource-scans.md)
        #skip_check: # Optional: Skip a specific check_id, can be a comma separated list
        #framework: # Optional: Run only on a specific infrastructure, one of: cloudformation, terraform, kubernetes, all
     env:  
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_SERVER_URL: $GITHUB_SERVER_URL
    - name: Expose report
      uses: actions/upload-artifact@v2
      with:
        name: SARIF results
        path: results.sarif
    # Uploads results.sarif to GitHub repository using the upload-sarif action
    - uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
